{{- $name := include "common.name" . -}}
{{- $fullname := include "common.fullname" . -}}
{{- $labels := include "common.labels" . -}}
{{- $selectorLabels := include "common.selectorLabels" . -}}
{{- $serviceAccountName := include "common.serviceAccountName" . -}}
{{- $injectAnnotation := include "common.injectAnnotation" . -}}
{{- $imagePullSecrets := .Values.imagePullSecrets -}}
{{- $imageTag := .Values.imageTag -}}
{{- $chartName := .Chart.Name -}}
{{- $chartAppVersion := .Chart.AppVersion -}}

{{- range $key, $value := .Values.workloads }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ $name }}-deployment-{{ $value.name }}
  {{- if eq $value.reloader "true" }}
  annotations:
    reloader.stakater.com/auto: "true"
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ $name }}-{{ $value.name }}
    {{- $labels | nindent 4 }}
spec:
  {{- if not $value.autoscaling.enabled }}
  replicas: {{ $value.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}-{{ $value.name }}
      app.kubernetes.io/component: {{ $value.name }}
      {{- $selectorLabels | nindent 6 }}
  strategy:
    canary:
      canaryService: {{ $fullname }}-service-preview-{{ $value.name }}
      steps:
      {{- toYaml $value.strategy.canary.steps | nindent 6 }}
  template:
    metadata:
      annotations:
        app.kubernetes.io/name: {{ $name }}-{{ $value.name }}
      {{- with $value.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $value.instrumentation.enabled }}
        {{- if eq $value.instrumentation.type "java" }}
        instrumentation.opentelemetry.io/inject-java: "true"
        {{- end }}
        {{- if eq $value.instrumentation.type  "dotnet" }}
        instrumentation.opentelemetry.io/inject-dotnet: "true"
        {{- end }}
        {{- if eq $value.instrumentation.type "go" }}
        instrumentation.opentelemetry.io/inject-go: "true"
        {{- end }}
        {{- if eq $value.instrumentation.type "nodejs" }}
        instrumentation.opentelemetry.io/inject-nodejs: "true"
        {{- end }}
        {{- if eq $value.instrumentation.type "python" }}
        instrumentation.opentelemetry.io/inject-python: "true"
        {{- end }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ $name }}-{{ $value.name }}
        app.kubernetes.io/component: {{ $value.name }}
        {{- $selectorLabels | nindent 8 }}
    spec:
      {{- if $value.priorityClassName }}
      priorityClassName: {{ $value.priorityClassName }}
      {{- end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: {{ $name }}-{{ $value.name }}
            app.kubernetes.io/component: {{ $value.name }}
            {{- $selectorLabels | nindent 12 }}
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: {{ $name }}-{{ $value.name }}
            app.kubernetes.io/component: {{ $value.name }}
            {{- $selectorLabels | nindent 12 }}
      {{- with $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        {{- toYaml $value.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ $name }}-{{ $value.name }}
                  app.kubernetes.io/component: {{ $value.name }}
                  {{- $selectorLabels | nindent 18 }}
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ $name }}-{{ $value.name }}
                  app.kubernetes.io/component: {{ $value.name }}
                  {{- $selectorLabels | nindent 18 }}
              topologyKey: kubernetes.io/hostname
            weight: 80
      volumes: 
        {{- if $value.volumes }}
        {{- toYaml $value.volumes | nindent 8 }}
        {{- end }}
        {{- if and ($value.externalSecret.extraVolumeMountsFromSecret) ($value.externalSecret.create) }}
        - name: {{ $value.externalSecret.name }}
          secret:
            secretName: {{ $value.externalSecret.name }}
        {{- end }}
      terminationGracePeriodSeconds: 120
      containers:
        - name: {{ $chartName }}
          {{- if $value.command }}
          command:
          {{- toYaml $value.command | nindent 10 }}
          {{- end }}
          {{- if $value.args }}
          args:
          {{- toYaml $value.args | nindent 10 }}
          {{- end }}
          securityContext:
            {{- toYaml $value.securityContext | nindent 12 }}
          {{- if $value.image.imageTag }}
          image: "{{ $value.image.repository }}:{{ $value.image.imageTag }}"
          {{- else }}
          image: "{{ $value.image.repository }}:{{ $imageTag | default $chartAppVersion }}"
          {{- end }}
          imagePullPolicy: {{ $value.image.pullPolicy }}
          {{- if $value.livenessProbe }}
          livenessProbe:
            {{- toYaml $value.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $value.readinessProbe }}
          readinessProbe:
            {{- toYaml $value.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if eq (kindOf $value.ports) "map" }}
          ports:
            - name: http
              containerPort: {{ $value.ports.containerPort }}
              protocol: TCP
          {{- else}}
          ports:
            {{- toYaml $value.ports | nindent 12 }}
          {{- end}}
          volumeMounts:
            {{- if $value.volumeMounts }}
            {{- toYaml $value.volumeMounts | nindent 12 }}
            {{- end }}
            {{- if $value.externalSecret.create }}
            {{- range $value.externalSecret.extraVolumeMountsFromSecret }}
            - name: {{ $value.externalSecret.name }}
              {{- range $key1, $value1 := . }}
                {{- if ne $key1 "name"}}
                  {{- $key1 | nindent 14 }}: {{ $value1 }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml $value.resources | nindent 12 }}
          
          {{- if $value.env }}
          env:
            {{- toYaml $value.env | nindent 12 }}
          {{- end }}
          
          {{- if or $value.configMapName $value.externalSecret.create }}
          envFrom:
            {{- if $value.configMapName }}
            - configMapRef:
                name: {{ $value.configMapName }}
            {{- end }}
            {{- if $value.externalSecret.create }}
            - secretRef:
                name: {{ $value.externalSecret.name }}
            {{- end }}
          {{- end }}
      {{- with $value.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $value.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}