{{- if .Values.externalSecret.create -}}

{{- if eq .Values.externalSecret.backendType "azureKeyVaults" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "common.externalSecretName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.externalSecret.userAssignedIdentityID }}
    keyvaultName: {{ .Values.externalSecret.keyvaultName }}      # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
{{- range $key, $value := .Values.externalSecret.data }}
        - |
          objectName: {{ $value.objectName }}
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
{{- end}}
    tenantId: {{ .Values.externalSecret.tenantId }}                # The tenant ID of the key vault
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
{{- range $key, $value := .Values.externalSecret.data }}
    - key: {{ $value.key }}                         # data field to populate
      objectName: {{ $value.objectName }}                      # name of the mounted content to sync; this could be the object name or the object alias
{{- end}}
    secretName: {{ .Values.externalSecret.name }}                     # name of the Kubernetes secret object
    type: Opaque 
    
{{- end }}

{{- end }}
