{{- $fullName := include "common.fullname" . -}}
{{- $labels := include "common.labels" . -}}
{{- $capabilities := .Capabilities -}}

{{- range $key, $value := .Values.workloads }}
---
{{- if $value.extraIngress }}
{{- if $value.extraIngress.enabled }}

{{- if and $value.extraIngress.className (not (semverCompare ">=1.18-0" $capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $value.extraIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $value.extraIngress.annotations "kubernetes.io/ingress.class" $value.extraIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" $capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $value.name }}-extra
  labels:
    {{- $labels | nindent 4 }}
  {{- with $value.extraIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $value.extraIngress.className (semverCompare ">=1.18-0" $capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $value.extraIngress.className }}
  {{- end }}
  {{- if $value.extraIngress.tls }}
  tls:
    {{- range $value.extraIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $value.extraIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-service-{{ $value.name }}
                {{- if .servicePort }}
                port:
                  number: {{ .servicePort }}
                {{- else }}
                port:
                  number: {{ $value.service.port }}
                {{- end }}
              {{- else }}
              serviceName: {{ $fullName }}-service-{{ $value.name }}
              {{- if .servicePort }}
              servicePort: {{ .servicePort }}
              {{- else }}
              servicePort: {{ $value.service.port }}
              {{- end }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}