apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrusmentation-{{ .Release.Name }}
spec:
  env:
    - name: OTEL_EXPORTER_OTLP_TIMEOUT
      value: "20"
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "{{ .Values.instrumentation.sampler | default "1"  }}"
    - name: SPLUNK_TRACE_RESPONSE_HEADER_ENABLED
      value: "true"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
  exporter:
    endpoint: {{ .Values.instrumentation.endpoint }}
  propagators:
    {{- if .Values.instrumentation.xray }}
      - xray
    {{- else }}
      - tracecontext
      - baggage
    {{- end }}
  sampler:
    type: parentbased_traceidratio
    argument: "{{ .Values.instrumentation.sampler | default "1"  }}"
  python:
    env:
      {{- if .Values.instrumentation.xray }}
      - name: OTEL_PYTHON_ID_GENERATOR
        value: xray
      {{- end }}
      - name: OTEL_PYTHON_INSTRUMENTATION_SANITIZE_REDIS
        value: "true"
      - name: OTEL_PYTHON_LOG_CORRELATION
        value: "true"
      - name: OTEL_LOG_LEVEL
        value: "debug"
      - name: OTEL_PYTHON_LOG_LEVEL
        value: "debug"
      - name: OTEL_TRACES_EXPORTER
        value: otlp_proto_http
      - name: OTEL_METRICS_EXPORTER
        value: none
      - name: OTEL_LOG_EXPORTER
        value: otlp_proto_http
      - name: OTEL_EXPORTER_OTLP_LOGS_PROTOCOL
        value: "http/protobuf"
