{{- $name := include "common.name" . -}}
{{- $fullname := include "common.fullname" . -}}
{{- $labels := include "common.labels" . -}}
{{- $selectorLabels := include "common.selectorLabels" . -}}

{{- range $key, $value := .Values.workloads }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-service-{{ $value.name }}
  labels:
    app.kubernetes.io/name: {{ $name }}-{{ $value.name }}
  {{- with $value.service.extenalLabel }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- $labels | nindent 4 }}
spec:
  type: {{ $value.service.type }}
  {{- if $value.service.port }}
  ports:
    - port: {{ $value.service.port }}
      targetPort: {{ $value.service.targetPort }}
      protocol: TCP
      name: http
  {{- else}}
  ports:
    {{- toYaml $value.service.ports | nindent 4 }}
  {{- end}}
  selector:
    {{- $selectorLabels | nindent 4 }}
    app.kubernetes.io/component: {{ $value.name }}
    app.kubernetes.io/name: {{ $name }}-{{ $value.name }}

{{- end }}
